import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const archivo = localFont({
  src: "../styles/fonts/archivo/Archivo-Variable-latin.woff2",
  weight: "100 900",
  variable: "--font-archivo",
  display: "swap",
});

const instrumentSans = localFont({
  src: "../styles/fonts/instrument-sans/InstrumentSans-Variable-latin.woff2",
  weight: "400 700",
  variable: "--font-instrument-sans",
  display: "swap",
});

const geistMono = localFont({
  src: "../styles/fonts/geist-mono/GeistMono-Variable-latin.woff2",
  weight: "100 900",
  variable: "--font-geist-mono",
  display: "swap",
  // Mono is the data/instrument face; it does not appear above the fold on
  // the brand site, so it must not compete for preload bandwidth.
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${instrumentSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
